### ISSUE TITLE
reference to `process` in ClassActionFactory throws error in browser.

### ISSUE THREAD

**Issue by tannerlyons** [aminpaks/redux-typed-actions#2]
In the following code, line 4 throws an error because process is undefined.
```
    function ClassActionFactory() {
        this.suffixes = {};
        this.registry = {};
        if (process && process.env && process.env.NODE_ENV === 'production') {
            this.env = 'production';
        }
        else {
            this.env = 'development';
        }
        this.setSuffixes({
            empty: '',
            start: '',
            success: ' Success',
            failure: ' Failure',
        });
    }
```
Chrome 61.0.3163.100, linux.

**Comment by aminpaks** [comment]
Would you tell me about your environment that you're using?
Are you using UMD bundles?

**Comment by tannerlyons** [comment]
Sorry about the empty issue! I accidentally clicked submit.

Yes I am using the umd bundle.

**Comment by tannerlyons** [comment]
Seems like `typeof  process !== 'undefined'` would be a reasonable solution? I can make a PR if you'd like

**Comment by aminpaks** [comment]
I see. 
So yes I will fix this issue ASAP.
For UMD bundles we need to set the env manually cause there's no way to clarify it.

**Comment by aminpaks** [comment]
Should be fine now, try version 0.1.4

**Comment by aminpaks** [comment]
@tannermeans thanks for opening the issue

**Comment by tannerlyons** [comment]
Quick fix! nice!
